version: '3.8'

services:
  betting-dashboard:
    build: .
    container_name: universal-betting-dashboard
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - ODDS_API_KEY=${ODDS_API_KEY:-demo_key}
      - APISPORTS_KEY=${APISPORTS_KEY:-demo_key}
      - FOOTBALL_DATA_KEY=${FOOTBALL_DATA_KEY:-demo_key}
    volumes:
      - ./logs:/app/logs  # Optional: mount logs directory
    restart: unless-stopped
    networks:
      - betting-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: betting-dashboard-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Optional: SSL certificates
    depends_on:
      - betting-dashboard
    restart: unless-stopped
    networks:
      - betting-network
    profiles:
      - production  # Only start with --profile production

networks:
  betting-network:
    driver: bridge

volumes:
  logs:
    driver: local