name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests>=2.31.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - lxml>=4.9.0
  - html5lib>=1.1
  - beautifulsoup4>=4.11.0
  - tenacity>=8.2.0
  - flask>=2.3.0
  - flask-cors>=4.0.0
  - flake8
  - pytest
