# FootyStats League Configuration
# Generated automatically with static fallback
# Generated: 2025-07-15 20:08:06

FOOTYSTATS_API_KEY = "b44de69d5777cd2c78d81d59a85d0a91154e836320016b53ecdc1f646fc95b97"

# 50 Major Soccer Leagues Configuration
FOOTYSTATS_LEAGUE_IDS = {
    "English Premier League": "premier-league",
    "English Championship": "championship",
    "Spanish La Liga": "la-liga",
    "Spanish LaLiga2": "laliga2",
    "German Bundesliga": "bundesliga",
    "German 2. Bundesliga": "2-bundesliga",
    "Italian Serie A": "serie-a",
    "Italian Serie B": "serie-b",
    "French Ligue 1": "ligue-1",
    "French Ligue 2": "ligue-2",
    "Dutch Eredivisie": "eredivisie",
    "Portuguese Primeira Liga": "primeira-liga",
    "Belgian Pro League": "pro-league",
    "Austrian Bundesliga": "austrian-bundesliga",
    "Swiss Super League": "super-league",
    "Norwegian Eliteserien": "eliteserien",
    "Swedish Allsvenskan": "allsvenskan",
    "Danish Superliga": "superliga",
    "Scottish Premiership": "premiership",
    "Turkish Super Lig": "super-lig",
    "Brazilian Serie A": "serie-a-brazil",
    "Argentine Primera División": "primera-division",
    "Argentine Primera Nacional": "primera-nacional",
    "Mexican Liga MX": "liga-mx",
    "US Major League Soccer": "mls",
    "Colombian Primera A": "primera-a",
    "Chilean Primera División": "primera-chile",
    "Uruguayan Primera División": "primera-uruguay",
    "Ecuadorian Serie A": "serie-a-ecuador",
    "Peruvian Primera División": "primera-peru",
    "Japanese J1 League": "j1-league",
    "Japanese J2 League": "j2-league",
    "South Korean K League 1": "k-league-1",
    "South Korean K League 2": "k-league-2",
    "Chinese Super League": "super-league-china",
    "Australian A-League": "a-league",
    "Indian Super League": "isl",
    "Saudi Pro League": "pro-league-saudi",
    "UAE Pro League": "pro-league-uae",
    "Qatari Stars League": "stars-league",
    "Russian Premier League": "premier-league-russia",
    "Ukrainian Premier League": "premier-league-ukraine",
    "Polish Ekstraklasa": "ekstraklasa",
    "Czech First League": "first-league-czech",
    "Croatian HNL": "hnl",
    "Serbian SuperLiga": "superliga-serbia",
    "Romanian Liga 1": "liga-1-romania",
    "Bulgarian First League": "first-league-bulgaria",
    "Greek Super League": "super-league-greece",
    "Cypriot First Division": "first-division-cyprus",
}
